### ISSUE TITLE
Access Violation when closing program 

### ISSUE THREAD

**Issue by DomAmato** [secondstory/ofxWMFVideoPlayer#9] opened 2015-01-17 12:05 UTC
I am getting errors on machines with nvidia cards, 550 ti, 610m, 755m SLI which is being caused by the releaseSharedTexture call in PresentEngine.cpp

specifically when

    wglDXUnregisterObjectNV(gl_handleD3D, &gl_handle);

is called. If I comment it out the program closes without error and reports successful when killing the present engines. 
I know that the documents at http://developer.download.nvidia.com/opengl/specs/WGL_NV_DX_interop.txt
say to unregister when the texture is no longer used but it seems to crash every time even with valid handles. Computers with ATI or Intel chips don't seem to be affected but it has been a bit since I tested it on one of those machines.

**Comment by fingerx** [comment] 2015-10-20 04:46
Hello,DomAmato.I have this problem.Can you fixed it?

**Comment by DomAmato** [comment] 2015-10-20 06:23
Check out my branch which addresses this issue
https://github.com/DomAmato/ofxWMFVideoPlayer

**Comment by fingerx** [comment] 2015-10-26 11:30
thanks DomAmato!

**Comment by donaldr** [comment] 2015-10-26 16:50
Hi! Don't know how this bug escaped our attention. I'll ping the dev who worked on this and have him take a gander when he gets back from vacation.

**Comment by philippelaulheret** [comment] 2015-11-05 18:16
Hi guys, sorry Don for dropping the ball on that one. So unfortunately I can't reproduce the bug on my machine (at least with the simple example that goes with the addon). However I noticed the releaseTexture code is called twice (which is a terrible idea) and that's probably what's causing the access violation on the second time. 
I'm going to try to find a pc on which the function crashes, but in the meantime if someone experiencing the bug could run the simple example, put a breakpoint on the problematic function and reply in this thread telling if the crash happens on the first execution of the function or the second time it would help finding a better solution than simply commenting out the function that is specified in the specs....

**Comment by DomAmato** [comment] 2015-11-05 20:08
The stack trace starts in ofxWMFVideoPlayerUtils::shutdown
 
    if (m_pEVRPresenter) { m_pEVRPresenter->releaseSharedTexture(); }
    SafeRelease(&m_pEVRPresenter);

Then in Presenter.h

    void releaseSharedTexture() { return m_pD3DPresentEngine->releaseSharedTexture(); };

finally crashing at the line I posted above. It doesn't seem to matter which line calls the releaseSharedTexture() function since both lead to the crash even with non null handles. I hope this helps, try loading a mov or mp4 file as I can replicate this problem on literally any pc with an nvidia card

**Comment by philippelaulheret** [comment] 2015-11-06 00:32
So I tried on 3 different machines, all having different nvidia cards and I couldn't get it to crash (note: how do you exit the application ? I press escape, or click on the x of the openGL window; closing the terminal window causes a crash but I think it's oF related as it doesn't call destructors properly)

You could try this modification maybe ? : 

````
void D3DPresentEngine::releaseSharedTexture()
{
	if (!gl_handleD3D) return;
	if (!gl_handle) return;
	wglDXUnlockObjectsNV(gl_handleD3D, 1, &gl_handle);
	wglDXUnregisterObjectNV(gl_handleD3D,gl_handle);
	gl_handle = 0;
	//glDeleteTextures(1, &gl_name);
	SAFE_RELEASE(d3d_shared_surface);
	SAFE_RELEASE(d3d_shared_texture);

}
````

**Comment by DomAmato** [comment] 2015-11-06 05:54
it no longer appears to be a problem in 0.9.0 when I tested it with the master branch, though thats weird. Im goona poke around more see if I can see what was causing it though feel free to close this issue. Ill reopen it if i discover the reason

**Comment by philippelaulheret** [comment] 2015-11-10 01:46
Okay, good then \o/ Thanks for your help and reporting :)

**Closed by philippelaulheret** 2015-11-10 01:46 UTC
